version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    read_only: true
    ports:
      - "9090:9090"

  elasticsearch:
    image: elastic/elasticsearch:8.14.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=test
    
  custom-vm-autoscaler:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: custom-vm-autoscaler
    command: ["./custom-vm-autoscaler", "run", "--config", "/tmp/autoscaler.yaml"]
    volumes:
      - "./../config/samples/autoscaler.yaml:/tmp/autoscaler.yaml"
    depends_on:
      - prometheus
      - elasticsearch
